default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode

development:
  <<: *default
  database: dj_set_generator_development

test:
  <<: *default
  database: dj_set_generator_test

production:
  <<: *default
  database: dj_set_generator_production
  username: dj_set_generator
  password: <%= ENV['DJ_SET_GENERATOR_DATABASE_PASSWORD'] %>
